/*
 * @file default_CVs.h
 */

#ifndef DEFAULT_CVS_H
#define DEFAULT_CVS_H

#include <Arduino.h>
#include <avr/pgmspace.h>

// 4 header items + 16 blocks of 5 servo items
// + 16 blocks of 5 servo items = 164 items
//constexpr size_t NUM_TOTAL_CVS = 4 + (16 * 5);
// defined in defines.h

// struct wrapper to hold a raw C-style array
struct CVArrayContainer {
    CVPair data[NUM_TOTAL_CVS];
};

// compile-time generator function returning the custom container struct
constexpr CVArrayContainer GenerateFactoryDefaultCVs() {
    CVArrayContainer container{};

    size_t index = 0;

    // Static headers
    container.data[index] = {CV_ACCESSORY_DECODER_ADDRESS_LSB, static_cast<uint16_t>(DEFAULT_ACCESSORY_DECODER_ADDRESS & 0xFF)};
    container.data[index++] = {CV_ACCESSORY_DECODER_ADDRESS_MSB, static_cast<uint16_t>(DEFAULT_ACCESSORY_DECODER_ADDRESS >> 8)};
    container.data[index++] = {CV_ACCESSORY_DECODER_SERVO_MOVE_TIME, SERVO_TIME};
    container.data[index++] = {CV_29_CONFIG, CV29_ACCESSORY_DECODER};

    // servo sections
    for (int i = 0; i < NUM_TURNOUTS; ++i) {
        int base = CV_USER_BASE_ADDRESS + (i * 5);
        container.data[index++] = {static_cast<uint16_t>(base + 0), SERVO_MIN};
        container.data[index++] = {static_cast<uint16_t>(base + 1), SERVO_MAX};
        container.data[index++] = {static_cast<uint16_t>(base + 2), SERVO_TIME};
        container.data[index++] = {static_cast<uint16_t>(base + 3), SERVO_CONFIG};
        container.data[index++] = {static_cast<uint16_t>(base + 4), SERVO_MIN};
    }

    for (int i = 0; i < NUM_TURNOUTS; ++i) {
        int base = CV_USER_BASE_ADDRESS_2 + (i * 5);
        container.data[index++] = {static_cast<uint16_t>(base + 0), SERVO_MIN};
        container.data[index++] = {static_cast<uint16_t>(base + 1), SERVO_MAX};
        container.data[index++] = {static_cast<uint16_t>(base + 2), SERVO_TIME};
        container.data[index++] = {static_cast<uint16_t>(base + 3), SERVO_CONFIG};
        container.data[index++] = {static_cast<uint16_t>(base + 4), SERVO_MIN};
    }

    container.data[index++] = {CV_ACCESSORY_DECODER_SERIAL_LSB, uint8_t(SERIAL_NUMBER - (SERIAL_NUMBER * 256))};
    container.data[index++] = {CV_ACCESSORY_DECODER_SERIAL_MSB, uint8_t(SERIAL_NUMBER / 256)};

    return container;
}

// Force compile-time calculation and store the array explicitly in FLASH memory
const CVArrayContainer FactoryDefaultContainer PROGMEM = GenerateFactoryDefaultCVs();

// Expose an easier reference alias to mimic your original array layout
const CVPair* const FactoryDefaultCVs = FactoryDefaultContainer.data;


/*
CVPair FactoryDefaultCVs [] =
{
  {CV_ACCESSORY_DECODER_ADDRESS_LSB, DEFAULT_ACCESSORY_DECODER_ADDRESS & 0xFF},
  {CV_ACCESSORY_DECODER_ADDRESS_MSB, DEFAULT_ACCESSORY_DECODER_ADDRESS >> 8},

  {CV_ACCESSORY_DECODER_SERVO_MOVE_TIME, SERVO_TIME},
  {CV_29_CONFIG, CV29_ACCESSORY_DECODER},


  {CV_USER_BASE_ADDRESS, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 1, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 2, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 3, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 4, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 5, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 6, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 7, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 8, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 9, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 10, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 11, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 12, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 13, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 14, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 15, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 16, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 17, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 18, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 19, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 20, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 21, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 22, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 23, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 24, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 25, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 26, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 27, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 28, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 29, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 30, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 31, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 32, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 33, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 34, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 35, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 36, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 37, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 38, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 39, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 40, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 41, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 42, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 43, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 44, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 45, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 46, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 47, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 48, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 49, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 50, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 51, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 52, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 53, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 54, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 55, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 56, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 57, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 58, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 59, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 60, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 61, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 62, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 63, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 64, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 65, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 66, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 67, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 68, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 69, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 70, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 71, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 72, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 73, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 74, SERVO_MIN},

  {CV_USER_BASE_ADDRESS + 75, SERVO_MIN},
  {CV_USER_BASE_ADDRESS + 76, SERVO_MAX},
  {CV_USER_BASE_ADDRESS + 77, SERVO_TIME},
  {CV_USER_BASE_ADDRESS + 78, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS + 79, SERVO_MIN},

// 16 on PCA9685 at 0x41 pwm2
  {CV_USER_BASE_ADDRESS_2, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 1, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 2, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 3, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 4, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 5, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 6, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 7, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 8, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 9, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 10, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 11, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 12, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 13, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 14, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 15, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 16, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 17, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 18, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 19, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 20, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 21, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 22, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 23, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 24, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 25, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 26, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 27, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 28, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 29, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 30, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 31, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 32, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 33, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 34, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 35, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 36, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 37, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 38, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 39, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 40, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 41, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 42, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 43, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 44, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 45, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 46, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 47, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 48, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 49, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 50, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 51, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 52, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 53, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 54, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 55, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 56, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 57, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 58, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 59, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 60, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 61, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 62, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 63, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 64, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 65, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 66, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 67, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 68, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 69, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 70, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 71, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 72, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 73, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 74, SERVO_MIN},

  {CV_USER_BASE_ADDRESS_2 + 75, SERVO_MIN},
  {CV_USER_BASE_ADDRESS_2 + 76, SERVO_MAX},
  {CV_USER_BASE_ADDRESS_2 + 77, SERVO_TIME},
  {CV_USER_BASE_ADDRESS_2 + 78, SERVO_CONFIG},
  {CV_USER_BASE_ADDRESS_2 + 79, SERVO_MIN},

  {CV_ACCESSORY_DECODER_SERIAL_LSB, uint8_t(SERIAL_NUMBER - (SERIAL_NUMBER * 256))},
  {CV_ACCESSORY_DECODER_SERIAL_MSB, uint8_t(SERIAL_NUMBER / 256)},

};
*/

#endif
